name: HoTS
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.13.0=py36h06a4308_0
  - astor=0.8.1=py36h06a4308_0
  - blas=1.0=mkl
  - boost=1.74.0=py36h355b2fd_3
  - boost-cpp=1.74.0=h9359b55_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.9.30=h06a4308_1
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2020.12.5=py36h06a4308_0
  - coverage=5.5=py36h27cfd23_2
  - cudatoolkit=9.2=0
  - cudnn=7.6.5=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py_2
  - cython=0.29.24=py36h295c915_0
  - dataclasses=0.8=pyh4f3eec9_6
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gast=0.5.2=pyhd3eb1b0_0
  - gettext=0.19.8.1=h73d1719_1008
  - grpcio=1.36.1=py36h2157cd5_1
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=67.1=he1b5a44_0
  - importlib-metadata=4.8.1=py36h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py36h2531618_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.70.0=h174f98d_0
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.0.10=hc3755c2_1005
  - libuuid=2.32.1=h7f98852_1000
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=h68273f3_2
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.4=py36h06a4308_0
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1l=h7f8727e_0
  - pandas=1.1.5=py36h284efc9_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=6.2.1=py36h6b7be26_0
  - pip=21.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - protobuf=3.17.2=py36h295c915_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.20.1=py36h726f1de_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.6.13=hb7a2778_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=5.4.1=py36h27cfd23_1
  - rdkit=2021.03.5=py36hbacbb34_0
  - readline=8.1=h46c0cb4_0
  - reportlab=3.5.68=py36h3e18861_0
  - scikit-learn=0.24.2=py36ha9443f7_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=49.6.0=py36h5fab9bb_3
  - six=1.16.0=pyhd3eb1b0_0
  - sqlalchemy=1.3.23=py36h8f6f2f9_0
  - sqlite=3.36.0=h9cd32fc_2
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he74679b_0
  - tensorflow-base=1.12.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36h06a4308_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py36h8f6f2f9_1
  - tqdm=4.62.2=pyhd3eb1b0_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - werkzeug=2.0.1=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=ha95c52a_0
prefix: /home/dlsrnsi/anaconda3/envs/HoTS
